In [2]:
import pandas as pd
data=pd.read_excel('EJIS_all_articles_v1.xlsx')
data.head()

,Journal_Title,URL,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_url,Author_Address,Author_email
0,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Security and privacy risks in drone-based last...,Issue 5,"Volume 33, 2024 - Issue 5",The consideration of drones for last mile deli...,"['Drone', 'identifier', 'last mile delivery', ...",Yu-Ju Tu,https://www.tandfonline.com/author/Tu%2C+Yu-Ju,"a Management Information Systems, National Che...",NaN
1,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Security and privacy risks in drone-based last...,Issue 5,"Volume 33, 2024 - Issue 5",The consideration of drones for last mile deli...,"['Drone', 'identifier', 'last mile delivery', ...",Selwyn Piramuthu,https://www.tandfonline.com/author/Piramuthu%2...,b Information Systems and Operations Managemen...,selwyn@ufl.edu
2,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Security by envelopment Ã¢â‚¬â€œ a novel appro...,Issue 5,"Volume 33, 2024 - Issue 5",Organisationsâ€™ increasing adoption of lightw...,"['Organisational data security', 'robotic proc...",Aleksandre Asatiani,https://www.tandfonline.com/author/Asatiani%2C...,"a Swedish Center for Digital Innovation, Unive...",aleksandre.asatiani@ait.gu.se
3,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Security by envelopment Ã¢â‚¬â€œ a novel appro...,Issue 5,"Volume 33, 2024 - Issue 5",Organisationsâ€™ increasing adoption of lightw...,"['Organisational data security', 'robotic proc...",Tuuli Hakkarainen,https://www.tandfonline.com/author/Hakkarainen...,"b Work, Organisation and Management Group, Uni...",NaN
4,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Security by envelopment Ã¢â‚¬â€œ a novel appro...,Issue 5,"Volume 33, 2024 - Issue 5",Organisationsâ€™ increasing adoption of lightw...,"['Organisational data security', 'robotic proc...",Kimmo Paaso,https://www.tandfonline.com/author/Paaso%2C+Kimmo,"HR Reporting and Business Intelligence, Wärtsi...",NaN

In [ ]:
#column types and null values
print(data.info())
print(data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2561 entries, 0 to 2560
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Journal_Title   2561 non-null   object
 1   URL             2561 non-null   object
 2   Article_Title   2561 non-null   object
 3   Volume_Issue    2561 non-null   object
 4   Month_Year      2561 non-null   object
 5   Abstract        2472 non-null   object
 6   Keywords        2561 non-null   object
 7   Author_name     2561 non-null   object
 8   Author_url      1931 non-null   object
 9   Author_Address  2557 non-null   object
 10  Author_email    629 non-null    object
dtypes: object(11)
memory usage: 220.2+ KB
None
Journal_Title        0
URL                  0
Article_Title        0
Volume_Issue         0
Month_Year           0
Abstract            89
Keywords             0
Author_name          0
Author_url         630
Author_Address       4
Author_email      1932
dtype: int64

In [ ]:
#drop rows with missing Author_Address
df = data.dropna(subset=['Author_Address'])

In [9]:
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2557 entries, 0 to 2560
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Journal_Title   2557 non-null   object
 1   URL             2557 non-null   object
 2   Article_Title   2557 non-null   object
 3   Volume_Issue    2557 non-null   object
 4   Month_Year      2557 non-null   object
 5   Abstract        2468 non-null   object
 6   Keywords        2557 non-null   object
 7   Author_name     2557 non-null   object
 8   Author_url      1927 non-null   object
 9   Author_Address  2557 non-null   object
 10  Author_email    629 non-null    object
dtypes: object(11)
memory usage: 239.7+ KB

In [ ]:
#fill remaining null values with 'NULL'
df = data.fillna('NULL')

In [5]:
print(data.describe())

                                            Journal_Title  \
count                                                2561
unique                                                133
top     European Journal of Information Systems, Volum...
freq                                                   46

                                                      URL Article_Title  \
count                                                2561          2561
unique                                               1027          1019
top     https://www.tandfonline.com/doi/full/10.1057/e...     Editorial
freq                                                   10            12

       Volume_Issue                                         Month_Year  \
count          2561                                               2561
unique           18                                                133
top         Issue 3  Volume 16, 2007 - Issue 4: Including a Special...
freq            447                                                 46

                                                 Abstract Keywords  \
count                                                2472     2561
unique                                                862      712
top     Information Systems Research (â€œWirtschaftsin...       []
freq                                                   10      215

        Author_name                                        Author_url  \
count          2561                                              1931
unique         1901                                              1444
top     Frantz Rowe  https://www.tandfonline.com/author/Paul%2C+Ray+J
freq             14                                                15

                                           Author_Address  \
count                                                2557
unique                                               2354
top     Department of Information Systems and Computin...
freq                                                   10

                  Author_email
count                      629
unique                     548
top     m.myers@auckland.ac.nz
freq                         5

In [ ]:
#check for duplicates incuding first occurrence
df[df.duplicated(keep=False)]

,Journal_Title,URL,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_url,Author_Address,Author_email
2442,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,"Information systems evaluation: past, present ...",Issue 4,"Volume 10, 2001 - Issue 4",NaN,[],Z Irani,NaN,Information Systems Evaluation and Integration...,NaN
2443,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,"Information systems evaluation: past, present ...",Issue 4,"Volume 10, 2001 - Issue 4",NaN,[],P E D Love,NaN,"School of Management Information Systems, Edit...",NaN
2444,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,Understanding IS evaluation as a complex socia...,Issue 4,"Volume 10, 2001 - Issue 4",The increasing concern from both IS practition...,[],S Jones,NaN,"Conwy County Borough Council, BodlondebConwyWa...",NaN
2445,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,Understanding IS evaluation as a complex socia...,Issue 4,"Volume 10, 2001 - Issue 4",The increasing concern from both IS practition...,[],J Hughes,NaN,"Information Systems Institute, University of S...",NaN
2446,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,A framework for the ex-ante evaluation of ERP ...,Issue 4,"Volume 10, 2001 - Issue 4",It has been widely reported that a large numbe...,[],C J Stefanou,NaN,Technological Educational Institution (TEI) of...,NaN
2447,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,ERP software implementation: an integrative fr...,Issue 4,"Volume 10, 2001 - Issue 4",ERP implementation is a socio-technical challe...,[],A Al-Mudimigh,NaN,"ECTQM, University of BradfordBradfordWest York...",NaN
2448,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,ERP software implementation: an integrative fr...,Issue 4,"Volume 10, 2001 - Issue 4",ERP implementation is a socio-technical challe...,[],M Zairi,NaN,"ECTQM, University of BradfordBradfordWest York...",NaN
2449,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,ERP software implementation: an integrative fr...,Issue 4,"Volume 10, 2001 - Issue 4",ERP implementation is a socio-technical challe...,[],M Al-Mashari,NaN,Department of Information SystemsCollege of Co...,NaN
2450,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,The impact of information technology on financ...,Issue 4,"Volume 10, 2001 - Issue 4",Information technology (IT) may not automatica...,[],N Shin,NaN,School of Computer Science and Information Sys...,NaN
2451,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,"Information systems evaluation: past, present ...",Issue 4,"Volume 10, 2001 - Issue 4",NaN,[],Z Irani,NaN,Information Systems Evaluation and Integration...,NaN
2452,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,"Information systems evaluation: past, present ...",Issue 4,"Volume 10, 2001 - Issue 4",NaN,[],P E D Love,NaN,"School of Management Information Systems, Edit...",NaN
2453,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,Understanding IS evaluation as a complex socia...,Issue 4,"Volume 10, 2001 - Issue 4",The increasing concern from both IS practition...,[],S Jones,NaN,"Conwy County Borough Council, BodlondebConwyWa...",NaN
2454,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,Understanding IS evaluation as a complex socia...,Issue 4,"Volume 10, 2001 - Issue 4",The increasing concern from both IS practition...,[],J Hughes,NaN,"Information Systems Institute, University of S...",NaN
2455,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,A framework for the ex-ante evaluation of ERP ...,Issue 4,"Volume 10, 2001 - Issue 4",It has been widely reported that a large numbe...,[],C J Stefanou,NaN,Technological Educational Institution (TEI) of...,NaN
2456,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,ERP software implementation: an integrative fr...,Issue 4,"Volume 10, 2001 - Issue 4",ERP implementation is a socio-technical challe...,[],A Al-Mudimigh,NaN,"ECTQM, University of BradfordBradfordWest York...",NaN
2457,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,ERP software implementation: an integrative fr...,Issue 4,"Volume 10, 2001 - Issue 4",ERP implementation is a socio-technical challe...,[],M Zairi,NaN,"ECTQM, University of BradfordBradfordWest York...",NaN
2458,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,ERP software implementation: an integrative fr...,Issue 4,"Volume 10, 2001 - Issue 4",ERP implementation is a socio-technical challe...,[],M Al-Mashari,NaN,Department of Information SystemsCollege of Co...,NaN
2459,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/abs/10.1057/pa...,The impact of information technology on financ...,Issue 4,"Volume 10, 2001 - Issue 4",Information technology (IT) may not automatica...,[],N Shin,NaN,School of Computer Science and Information Sys...,NaN

In [ ]:
#drop duplicates, keeping first occurrence
df.drop_duplicates(inplace=True)

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_52179/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

0

In [ ]:
#check for empty strings
df.columns[(df==" ").any()]

Index([], dtype='object')

In [20]:
df.to_excel('EJIS_all_articles_cleaned_v1.xlsx', index=False)

In [13]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')
    
cursor = db.cursor()
# Insert data into MySQL
for index, row in df.iterrows():
    standard_name=row["Standardized_Name"] if row['Standardized_Name'] else None
    # keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    # url=row["URL"] if row['URL'] else None
    # journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    # volume_issue=row["Volume_Issue"] if row['Volume_Issue'] else None
    # month_year=row["Month_Year"] if row['Month_Year'] else None
    # abstract=row["Abstract"] if row['Abstract'] else None
    author_name=row["Author_Name"] if row['Author_Name'] else None
    # author_email=row["Author_Email"] if row['Author_Email'] else None
    # author_address=row["Author_Address"] if row['Author_Address'] else None
    

    try:
        sql = """
        Update Journal_Articles
        set Standardized_Name=%s
        where author_name=%s;
        """
        values = (
            standard_name,author_name
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Vol Issue Year"] if row["Vol Issue Year"] else None

    try:
        sql = """
        INSERT INTO DecisionSupportSystems
        (Title, URL, vol_issue_year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [1]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM Journal_Articles"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("Journal_Articles_new.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_99855/2316557836.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx