In [30]:
import pandas as pd
data=pd.read_csv('extract.csv')
data.head()

,URL,Journal_Title,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Standardized_Author,Author_email,Author_Address,Author_University,Author_department,Author_State,Author_Country,Author_pincode
0,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security and privacy risks in drone-based last...,Issue 5,"Volume 33, 2024 - Issue 5",The consideration of drones for last mile deli...,"['Drone', 'identifier', 'last mile delivery', ...",Yu-Ju Tu,Yu-Ju Tua,NaN,"a Management Information Systems, National Che...",National Chengchi University,Management Information Systems,Taipei,Taiwan,NaN
1,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security and privacy risks in drone-based last...,Issue 5,"Volume 33, 2024 - Issue 5",The consideration of drones for last mile deli...,"['Drone', 'identifier', 'last mile delivery', ...",Selwyn Piramuthu,Selwyn Piramuthu,selwyn@ufl.edu,b Information Systems and Operations Managemen...,University of Florida,Information Systems and Operations Management,Florida,United States,NaN
2,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security by envelopment √É¬¢√¢‚Äö¬¨√¢‚Ç¨≈ì a n...,Issue 5,"Volume 33, 2024 - Issue 5",Organisations√¢‚Ç¨‚Ñ¢ increasing adoption of l...,"['Organisational data security', 'robotic proc...",Aleksandre Asatiani,Aleksandre Asatiania,aleksandre.asatiani@ait.gu.se,"a Swedish Center for Digital Innovation, Unive...",University of Gothenburg,Swedish Center for Digital Innovation,V√§stra G√∂taland,Sweden,NaN
3,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security by envelopment √É¬¢√¢‚Äö¬¨√¢‚Ç¨≈ì a n...,Issue 5,"Volume 33, 2024 - Issue 5",Organisations√¢‚Ç¨‚Ñ¢ increasing adoption of l...,"['Organisational data security', 'robotic proc...",Tuuli Hakkarainen,Tuuli Hakkarainen,NaN,"b Work, Organisation and Management Group, Uni...",University of Liverpool,"Work, Organisation and Management Group",Liverpool,United Kingdom,NaN
4,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security by envelopment √É¬¢√¢‚Äö¬¨√¢‚Ç¨≈ì a n...,Issue 5,"Volume 33, 2024 - Issue 5",Organisations√¢‚Ç¨‚Ñ¢ increasing adoption of l...,"['Organisational data security', 'robotic proc...",Kimmo Paaso,Kimmo Paaso,NaN,"HR Reporting and Business Intelligence, W√§rts...",W√§rtsil√§ Corporation,HR Reporting and Business Intelligence,Uusimaa,Finland,NaN

In [31]:
#column types and null values
print(data.info())
print(data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2548 entries, 0 to 2547
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   URL                  2548 non-null   object
 1   Journal_Title        2548 non-null   object
 2   Article_Title        2548 non-null   object
 3   Volume_Issue         2548 non-null   object
 4   Month_Year           2548 non-null   object
 5   Abstract             2461 non-null   object
 6   Keywords             2548 non-null   object
 7   Author_name          2548 non-null   object
 8   Standardized_Author  2548 non-null   object
 9   Author_email         629 non-null    object
 10  Author_Address       2548 non-null   object
 11  Author_University    2540 non-null   object
 12  Author_department    2030 non-null   object
 13  Author_State         2452 non-null   object
 14  Author_Country       2542 non-null   object
 15  Author_pincode       212 non-null    object
dtypes: object(16)
memory usage: 318.6+ KB
None
URL                       0
Journal_Title             0
Article_Title             0
Volume_Issue              0
Month_Year                0
Abstract                 87
Keywords                  0
Author_name               0
Standardized_Author       0
Author_email           1919
Author_Address            0
Author_University         8
Author_department       518
Author_State             96
Author_Country            6
Author_pincode         2336
dtype: int64

In [32]:
#drop rows with missing Author_Address
data = data.dropna(subset=['Author_Address'])

In [33]:
#fill remaining null values with 'NULL'
data = data.fillna('NULL')

In [34]:
print(data.describe())

                                                      URL  \
count                                                2548
unique                                               1027
top     https://www.tandfonline.com/doi/full/10.1057/e...
freq                                                   10

                                            Journal_Title Article_Title  \
count                                                2548          2548
unique                                                133          1019
top     European Journal of Information Systems, Volum...     Editorial
freq                                                   46            12

       Volume_Issue                                         Month_Year  \
count          2548                                               2548
unique           18                                                133
top         Issue 3  Volume 16, 2007 - Issue 4: Including a Special...
freq            447                                                 46

       Abstract Keywords  Author_name Standardized_Author Author_email  \
count      2548     2548         2548                2548         2548
unique      863      712         1900                1892          549
top        NULL       []  Frantz Rowe            Ray Paul         NULL
freq         87      206           14                  22         1919

                                           Author_Address  Author_University  \
count                                                2548               2548
unique                                               2354                855
top     Department of Information Systems and Computin...  Brunel University
freq                                                   10                 73

       Author_department Author_State Author_Country Author_pincode
count               2548         2548           2548           2548
unique               673          319             51            148
top                 NULL         NULL  United States           NULL
freq                 518           96            856           2336

In [35]:
#check for duplicates incuding first occurrence
data[data.duplicated(keep=False)]

Empty DataFrame
Columns: [URL, Journal_Title, Article_Title, Volume_Issue, Month_Year, Abstract, Keywords, Author_name, Standardized_Author, Author_email, Author_Address, Author_University, Author_department, Author_State, Author_Country, Author_pincode]
Index: []

In [36]:
#drop duplicates, keeping first occurrence
data.drop_duplicates(inplace=True)

In [37]:
data.duplicated().sum()

0

In [ ]:
#check for empty strings
df.columns[(df==" ").any()]

Index([], dtype='object')

In [38]:
data['Year'] = data['Month_Year'].apply(lambda x: x.split(' ')[2].strip())
print(data['Year'])

0       2024
1       2024
2       2024
3       2024
4       2024
        ...
2543    2000
2544    2000
2545    2000
2546    2000
2547    2000
Name: Year, Length: 2548, dtype: object

In [39]:
data.head()

,URL,Journal_Title,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Standardized_Author,Author_email,Author_Address,Author_University,Author_department,Author_State,Author_Country,Author_pincode,Year
0,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security and privacy risks in drone-based last...,Issue 5,"Volume 33, 2024 - Issue 5",The consideration of drones for last mile deli...,"['Drone', 'identifier', 'last mile delivery', ...",Yu-Ju Tu,Yu-Ju Tua,NULL,"a Management Information Systems, National Che...",National Chengchi University,Management Information Systems,Taipei,Taiwan,NULL,2024
1,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security and privacy risks in drone-based last...,Issue 5,"Volume 33, 2024 - Issue 5",The consideration of drones for last mile deli...,"['Drone', 'identifier', 'last mile delivery', ...",Selwyn Piramuthu,Selwyn Piramuthu,selwyn@ufl.edu,b Information Systems and Operations Managemen...,University of Florida,Information Systems and Operations Management,Florida,United States,NULL,2024
2,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security by envelopment √É¬¢√¢‚Äö¬¨√¢‚Ç¨≈ì a n...,Issue 5,"Volume 33, 2024 - Issue 5",Organisations√¢‚Ç¨‚Ñ¢ increasing adoption of l...,"['Organisational data security', 'robotic proc...",Aleksandre Asatiani,Aleksandre Asatiania,aleksandre.asatiani@ait.gu.se,"a Swedish Center for Digital Innovation, Unive...",University of Gothenburg,Swedish Center for Digital Innovation,V√§stra G√∂taland,Sweden,NULL,2024
3,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security by envelopment √É¬¢√¢‚Äö¬¨√¢‚Ç¨≈ì a n...,Issue 5,"Volume 33, 2024 - Issue 5",Organisations√¢‚Ç¨‚Ñ¢ increasing adoption of l...,"['Organisational data security', 'robotic proc...",Tuuli Hakkarainen,Tuuli Hakkarainen,NULL,"b Work, Organisation and Management Group, Uni...",University of Liverpool,"Work, Organisation and Management Group",Liverpool,United Kingdom,NULL,2024
4,https://www.tandfonline.com/doi/full/10.1080/0...,"European Journal of Information Systems, Volum...",Security by envelopment √É¬¢√¢‚Äö¬¨√¢‚Ç¨≈ì a n...,Issue 5,"Volume 33, 2024 - Issue 5",Organisations√¢‚Ç¨‚Ñ¢ increasing adoption of l...,"['Organisational data security', 'robotic proc...",Kimmo Paaso,Kimmo Paaso,NULL,"HR Reporting and Business Intelligence, W√§rts...",W√§rtsil√§ Corporation,HR Reporting and Business Intelligence,Uusimaa,Finland,NULL,2024

In [20]:
df.to_excel('EJIS_all_articles_cleaned_v1.xlsx', index=False)

In [40]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

cursor = db.cursor()

for index, row in data.iterrows():
    url=row["URL"] if row['URL'] else None
    article_title=row["Article_Title"] if row['Article_Title'] else None
    journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    abstract=row["Abstract"] if row['Abstract'] else None
    keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    month_year=row["Year"] if row['Year'] else None
    author_name=row["Author_name"] if row['Author_name'] else None
    standard_name=row["Standardized_Author"] if row['Standardized_Author'] else None
    author_email=row["Author_email"] if row['Author_email'] else None
    author_address=row["Author_Address"] if row['Author_Address'] else None
    author_university=row["Author_University"] if row['Author_University'] else None
    author_department=row["Author_department"] if row['Author_department'] else None
    author_state=row["Author_State"] if row['Author_State'] else None  #   
    author_country=row["Author_Country"] if row['Author_Country'] else None
        
    try:
        sql = """
        INSERT INTO EJIS(URL,Journal_Title,Article_Title,Abstract,Keywords,Month_Year,Author_name,Standardized_Author,Author_email,Author_Address,Author_University,Author_Department,Author_State,Author_Country) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """
        values = (
            url,journal_title,article_title,abstract,keywords,month_year,author_name,standard_name,author_email,author_address,author_university,author_department,author_state,author_country
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Vol Issue Year"] if row["Vol Issue Year"] else None

    try:
        sql = """
        INSERT INTO DecisionSupportSystems
        (Title, URL, vol_issue_year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [1]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM Journal_Articles"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("Journal_Articles_new.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_99855/2316557836.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx