In [20]:
import pandas as pd
data=pd.read_csv('EJIS_2025_articledata.csv')
data.head()

,Journal_Title,URL,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_Address,Author_email
0,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,Issue 5,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Christoph F. Breidbach,"a Business School, The University of Queenslan...",NaN
1,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,Issue 5,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Amol M. Joshi,"b School of Business, Wake Forest University, ...",NaN
2,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,Issue 5,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Alexander Twigg,"c Shift Happens Group, Sydney, AustraliaView f...",NaN
3,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,Issue 5,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Graham Dickens,"d Wayfinder5, Melbourne, AustraliaView further...",NaN
4,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Responsible social media use: how user charact...,Issue 5,"Volume 34, 2025 - Issue 5",Social media’s dual role as a source of both s...,"['Responsibility', 'IS use', 'affordances', 'a...",Raffaele Ciriello,"a Business Information Systems Discipline, Uni...",NaN

In [52]:
data.drop(columns=['Volume_Issue','Author_email'],inplace=True)

In [22]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Journal_Title   234 non-null    object
 1   URL             234 non-null    object
 2   Article_Title   234 non-null    object
 3   Volume_Issue    234 non-null    object
 4   Month_Year      232 non-null    object
 5   Abstract        230 non-null    object
 6   Keywords        234 non-null    object
 7   Author_name     233 non-null    object
 8   Author_Address  233 non-null    object
 9   Author_email    0 non-null      float64
dtypes: float64(1), object(9)
memory usage: 18.4+ KB
None

In [34]:
#drop rows with missing Author_Address
data = data.dropna(subset=['Author_Address'])

In [36]:
data.isnull().sum()

Journal_Title       0
URL                 0
Article_Title       0
Volume_Issue        0
Month_Year          0
Abstract            4
Keywords            0
Author_name         0
Author_Address      0
Author_email      233
dtype: int64

In [35]:
#find the data where month_year value is 'NULL'
data[data['Month_Year'].isnull()]

Empty DataFrame
Columns: [Journal_Title, URL, Article_Title, Volume_Issue, Month_Year, Abstract, Keywords, Author_name, Author_Address, Author_email]
Index: []

In [28]:
#fill the month year column null value with last available value
data['Month_Year'].fillna(method='ffill', inplace=True)

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_77216/1310016746.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Month_Year'].fillna(method='ffill', inplace=True)
/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_77216/1310016746.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Month_Year'].fillna(method='ffill', inplace=True)

In [38]:
data.duplicated().sum()

60

In [39]:
#check for duplicates incuding first occurrence
data[data.duplicated(keep=False)]

,Journal_Title,URL,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_Address,Author_email
57,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,To learn or not learn from AI? Unpacking the e...,Issue 4,"Volume 34, 2025 - Issue 4",Artificial intelligence (AI) tools are unique ...,"['Artificial intelligence', 'AI', 'learning', ...",Ofir Turel,"Computing and Information Systems, University ...",NaN
58,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,To learn or not learn from AI? Unpacking the e...,Issue 4,"Volume 34, 2025 - Issue 4",Artificial intelligence (AI) tools are unique ...,"['Artificial intelligence', 'AI', 'learning', ...",Ofir Turel,"Computing and Information Systems, University ...",NaN
59,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,To learn or not learn from AI? Unpacking the e...,Issue 4,"Volume 34, 2025 - Issue 4",Artificial intelligence (AI) tools are unique ...,"['Artificial intelligence', 'AI', 'learning', ...",Ofir Turel,"Computing and Information Systems, University ...",NaN
60,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,To learn or not learn from AI? Unpacking the e...,Issue 4,"Volume 34, 2025 - Issue 4",Artificial intelligence (AI) tools are unique ...,"['Artificial intelligence', 'AI', 'learning', ...",Ofir Turel,"Computing and Information Systems, University ...",NaN
61,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,To learn or not learn from AI? Unpacking the e...,Issue 4,"Volume 34, 2025 - Issue 4",Artificial intelligence (AI) tools are unique ...,"['Artificial intelligence', 'AI', 'learning', ...",Ofir Turel,"Computing and Information Systems, University ...",NaN
...,...,...,...,...,...,...,...,...,...,...
229,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Realising the potential of digital health comm...,Issue 6,"Volume 33, 2024 - Issue 6",Health and fitness communities in the digital ...,"['Digital health community', 'continuance inte...",Kaushalya Nallaperuma,a Department of Information Systems and Busine...,NaN
230,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Realising the potential of digital health comm...,Issue 6,"Volume 33, 2024 - Issue 6",Health and fitness communities in the digital ...,"['Digital health community', 'continuance inte...",Lemai Nguyen,a Department of Information Systems and Busine...,NaN
231,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Realising the potential of digital health comm...,Issue 6,"Volume 33, 2024 - Issue 6",Health and fitness communities in the digital ...,"['Digital health community', 'continuance inte...",Ojelanki Ngwenyama,"b Ted Rogers School of Management, Toronto Met...",NaN
232,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Realising the potential of digital health comm...,Issue 6,"Volume 33, 2024 - Issue 6",Health and fitness communities in the digital ...,"['Digital health community', 'continuance inte...",Argho Bandyopadhyay,"d Graduate School of Business and Law, RMIT Un...",NaN
233,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Realising the potential of digital health comm...,Issue 6,"Volume 33, 2024 - Issue 6",Health and fitness communities in the digital ...,"['Digital health community', 'continuance inte...",Kaushalya Nallaperuma,a Department of Information Systems and Busine...,NaN

In [41]:
#drop duplicates, keeping first occurrence
data.drop_duplicates(inplace=True)

In [42]:
data.duplicated().sum()

0

In [45]:
data.nunique()

Journal_Title       6
URL                50
Article_Title      50
Volume_Issue        6
Month_Year          6
Abstract           49
Keywords           50
Author_name       160
Author_Address    159
Author_email        0
dtype: int64

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 173 entries, 0 to 217
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Journal_Title   173 non-null    object
 1   URL             173 non-null    object
 2   Article_Title   173 non-null    object
 3   Volume_Issue    173 non-null    object
 4   Month_Year      173 non-null    object
 5   Abstract        169 non-null    object
 6   Keywords        173 non-null    object
 7   Author_name     173 non-null    object
 8   Author_Address  173 non-null    object
 9   Author_email    0 non-null      float64
dtypes: float64(1), object(9)
memory usage: 14.9+ KB

In [ ]:
#check for empty strings

Index([], dtype='object')

In [47]:
data['Year'] = data['Month_Year'].apply(lambda x: x.split(' ')[2].strip())
print(data['Year'])

0      2025
1      2025
2      2025
3      2025
4      2025
       ...
213    2024
214    2024
215    2024
216    2024
217    2024
Name: Year, Length: 173, dtype: object

In [53]:
data.head()

,Journal_Title,URL,Article_Title,Month_Year,Abstract,Keywords,Author_name,Author_Address,Year
0,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Christoph F. Breidbach,"a Business School, The University of Queenslan...",2025
1,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Amol M. Joshi,"b School of Business, Wake Forest University, ...",2025
2,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Alexander Twigg,"c Shift Happens Group, Sydney, AustraliaView f...",2025
3,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Orchestrating Digital Resilience: A Clinical I...,"Volume 34, 2025 - Issue 5",Organisations must build digital resilience to...,"['Digital resilience', 'orchestration', 'servi...",Graham Dickens,"d Wayfinder5, Melbourne, AustraliaView further...",2025
4,"European Journal of Information Systems, Volum...",https://www.tandfonline.com/doi/full/10.1080/0...,Responsible social media use: how user charact...,"Volume 34, 2025 - Issue 5",Social media’s dual role as a source of both s...,"['Responsibility', 'IS use', 'affordances', 'a...",Raffaele Ciriello,"a Business Information Systems Discipline, Uni...",2025

In [ ]:
import openai
import pandas as pd
import json
import csv
import os
# data=pd.read_excel('EJIS_all_articles_cleaned_v1.xlsx')
openai_api_key = os.getenv("OPENAI_API_KEY")
# print(openai_api_key)

def extract_author_address(author_address):
    # prompt=f"""
    # Extract the following details from this web journal articles url
    # URL	Author_Name	Standardized_Name	Standardized_University	Author_University	Author_Department	Author_State	Author_Country	Author_Pincode	title
    # # If any detail is missing, return NULL for that field and make sure maintain the same name for field values to search by that. 
    # # ex: in one record US and other record USA and other record contains United States of america display common name for these 3 record values. Same for university, department, state names also if Wichita State University in one record and WSU in other record display common name to use in search operation in my website. 
    # # If it is common name I can search easily.
    
    # # URL: {address}
    
    # # Return the data in JSON format.
    # """

    prompt = f"""
    Extract and standardize the following details from the given text containing author information:
    
    
        IMPORTANT LANGUAGE REQUIREMENTS:
        - Convert ALL text to English equivalents
        - Transliterate non-English characters to English alphabet (e.g., ñ→n, ü→u, é→e, ç→c)
        - Translate foreign language university names to their official English names
        - If university has both local and English names, use the English version
        - For author names with non-English characters, provide romanized/English alphabet version
        
        Fields to extract:
        - Author: Full name as mentioned in the text (converted to English alphabet)
        - Standardized_Author: Normalized English version for deduplication (follow rules below)
        - University: Full university name in English (standardize abbreviations and translate foreign names)
        - Department: Academic department in English (if mentioned, otherwise null)
        - State: State/province in English where the university is located
        - Country: Country name in standard English
        - Pincode: Postal/ZIP code (if mentioned, otherwise null)

        Author Name Standardization Rules:
        1. Convert to English alphabet (transliterate non-English characters)
        2. Use title case (First Letter Capitalized For Each Word)
        3. For names like "Rajesh R" and "Rajesh Raj" - if first name + first letter of last name matches, use the longer version
        4. Remove middle initials if a full middle name exists elsewhere for same person
        5. Handle common variations:
        - "Dr. John Smith" → "John Smith"
        - "Prof. Jane Doe" → "Jane Doe" 
        - "Smith, John" → "John Smith"
        - "J. Smith" vs "John Smith" → use "John Smith" if both refer to same person
        6. Remove extra spaces and special characters
        7. Convert accented characters: José → Jose, François → Francois, etc.

        University/Location Standardization Examples:
        - Universidad Politécnica de Madrid → "Technical University of Madrid"
        - WSU → "Wichita State University"
        - MIT → "Massachusetts Institute of Technology"
        - École Polytechnique → "Polytechnic School"
        - Université de Paris → "University of Paris"
        - Tsinghua Daxue → "Tsinghua University"
        - Universidad Nacional de Colombia → "National University of Colombia"
        - Technische Universität München → "Technical University of Munich"
        
        Country Standardization:
        - US/USA/United States/Estados Unidos → "United States"
        - UK/United Kingdom/Inglaterra → "United Kingdom"  
        - Deutschland/Alemania → "Germany"
        - España → "Spain"
        - França/France → "France"
        - Use full English country names

        State Standardization:
        - Use full English state/province names
        - CA → "California", NY → "New York", etc.
        - Convert regional names to English equivalents

        Text to process: {author_address}

        CRITICAL: Return ONLY as a single JSON object (not array) with English text only. Example format:
        {{
            "Author": "Jose Martinez",
            "Standardized_Author": "Jose Martinez", 
            "University": "Technical University of Madrid",
            "Department": "Computer Science",
            "State": "Madrid",
            "Country": "Spain",
            "Pincode": "28040"
        }}"""
    response=openai.chat.completions.create(
        model='gpt-3.5-turbo',
        messages=[
            {"role":"system","content":"You are an expert in structured data extraction."},
            {"role":"user","content":prompt}
        ],
        temperature=0
    )
    extracted_data=response.choices[0].message.content.strip().strip('```json').strip('```')
    try:
        structured_data=json.loads(extracted_data)
    except Exception as e:
        print(e)
    author_data={
        'Standardized_Author': structured_data.get('Standardized_Author', None),
        'University': structured_data.get('University', None),
        'Department': structured_data.get('Department', None),
        'State': structured_data.get('State', None),
        'Country': structured_data.get('Country', None),
        'Pincode': structured_data.get('Pincode', None) # assuming pincode is always present in the structured data. If not, return None.
    }  
    return author_data


with open('extract_2025.csv', mode='a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['URL','Journal_Title','Article_Title','Month_Year','Abstract','Keywords','Author_name','Standardized_Author','Author_Address','Author_University','Author_department','Author_State','Author_Country'])
for index,row in data.iterrows():
    address=row['Author_name']+row['Author_Address']
    result = extract_author_address(address)
    with open('extract_2025.csv', mode='a', newline='',encoding='utf-8') as file:
        writer=csv.writer(file)
        writer.writerow([row['URL'],row['Journal_Title'],row['Article_Title'],row['Year'],row['Abstract'],row['Keywords'],row['Author_name'],result['Standardized_Author'],row['Author_Address'],result['University'],result['Department'],result['State'],result['Country']])

In [12]:
data.to_excel('EJIS_all_articles_cleaned_v1.xlsx', index=False)

In [40]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

cursor = db.cursor()

for index, row in data.iterrows():
    url=row["URL"] if row['URL'] else None
    article_title=row["Article_Title"] if row['Article_Title'] else None
    journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    abstract=row["Abstract"] if row['Abstract'] else None
    keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    month_year=row["Year"] if row['Year'] else None
    author_name=row["Author_name"] if row['Author_name'] else None
    standard_name=row["Standardized_Author"] if row['Standardized_Author'] else None
    author_email=row["Author_email"] if row['Author_email'] else None
    author_address=row["Author_Address"] if row['Author_Address'] else None
    author_university=row["Author_University"] if row['Author_University'] else None
    author_department=row["Author_department"] if row['Author_department'] else None
    author_state=row["Author_State"] if row['Author_State'] else None  #   
    author_country=row["Author_Country"] if row['Author_Country'] else None
        
    try:
        sql = """
        INSERT INTO EJIS(URL,Journal_Title,Article_Title,Abstract,Keywords,Month_Year,Author_name,Standardized_Author,Author_email,Author_Address,Author_University,Author_Department,Author_State,Author_Country) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """
        values = (
            url,journal_title,article_title,abstract,keywords,month_year,author_name,standard_name,author_email,author_address,author_university,author_department,author_state,author_country
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Vol Issue Year"] if row["Vol Issue Year"] else None

    try:
        sql = """
        INSERT INTO DecisionSupportSystems
        (Title, URL, vol_issue_year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [1]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM Journal_Articles"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("Journal_Articles_new.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_99855/2316557836.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx