In [ ]:
import pandas as pd
data=pd.read_excel('JMIS_Articles_new.xlsx')
data.head()

,Journal_Title,URL,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_Address
0,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,Issue 4,"Volume 41, 2024 - Issue 4",NaN,[],Corey Angst,Corey Angst (cangst@nd.edu) is the Jack and Jo...
1,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,Issue 4,"Volume 41, 2024 - Issue 4",NaN,[],Alan R. Dennis,Alan R. Dennis (ardennis@iu.edu; corresponding...
2,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,Issue 4,"Volume 41, 2024 - Issue 4",NaN,[],Elena Karahanna,Elena Karahanna (ekarah@uga.edu) is Distinguis...
3,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,Issue 4,"Volume 41, 2024 - Issue 4",NaN,[],Gondy Leroy,Gondy Leroy (gondyleroy@arizona.edu) is Profes...
4,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Digital Phenotyping-based Depression Detection...,Issue 4,"Volume 41, 2024 - Issue 4",Depression is a growing health and societal pr...,"['Digital phenotyping', 'mobile health analyti...",Fei Peng,Fei Peng is a PhD candidate in the Department ...

In [12]:
data.drop('Volume_Issue',axis=1, inplace=True)

In [13]:
print(data.info())
print(data.isnull().sum())
print(data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2718 entries, 0 to 2717
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Journal_Title   2718 non-null   object
 1   URL             2718 non-null   object
 2   Article_Title   2718 non-null   object
 3   Month_Year      2718 non-null   object
 4   Abstract        2561 non-null   object
 5   Keywords        2718 non-null   object
 6   Author_name     2718 non-null   object
 7   Author_Address  2717 non-null   object
dtypes: object(8)
memory usage: 170.0+ KB
None
Journal_Title       0
URL                 0
Article_Title       0
Month_Year          0
Abstract          157
Keywords            0
Author_name         0
Author_Address      1
dtype: int64
                                            Journal_Title  \
count                                                2718
unique                                                 77
top     Journal of Management Information Systems, Vol...
freq                                                   96

                                                      URL  \
count                                                2718
unique                                                817
top     https://www.tandfonline.com/doi/full/10.1080/0...
freq                                                   18

                                            Article_Title  \
count                                                2718
unique                                                816
top     Enhancing Predictive Analytics for Anti-Phishi...
freq                                                   18

                       Month_Year  \
count                        2718
unique                         77
top     Volume 31, 2015 - Issue 4
freq                           96

                                                 Abstract Keywords  \
count                                                2561     2718
unique                                                766      765
top     Phishing websites continue to successfully exp...       []
freq                                                   18      162

             Author_name                              Author_Address
count               2718                                        2717
unique              1650                                        2225
top     Jay F. Nunamaker  Wharton School, University of Pennsylvania
freq                  37                                          11

In [14]:

df = data.fillna('NULL')

In [15]:
print(data.describe())

                                            Journal_Title  \
count                                                2718
unique                                                 77
top     Journal of Management Information Systems, Vol...
freq                                                   96

                                                      URL  \
count                                                2718
unique                                                817
top     https://www.tandfonline.com/doi/full/10.1080/0...
freq                                                   18

                                            Article_Title  \
count                                                2718
unique                                                816
top     Enhancing Predictive Analytics for Anti-Phishi...
freq                                                   18

                       Month_Year  \
count                        2718
unique                         77
top     Volume 31, 2015 - Issue 4
freq                           96

                                                 Abstract Keywords  \
count                                                2561     2718
unique                                                766      765
top     Phishing websites continue to successfully exp...       []
freq                                                   18      162

             Author_name                              Author_Address
count               2718                                        2717
unique              1650                                        2225
top     Jay F. Nunamaker  Wharton School, University of Pennsylvania
freq                  37                                          11

In [16]:
df = data.where(pd.notna(data), None)

In [17]:
df = data.replace("", None)  # Replaces empty spaces with None

In [18]:
df['Year'] = df['Month_Year'].apply(lambda x: x.split(',')[1].strip().split()[0])
df['Year'] = df['Year'].astype(int)

In [21]:
df.head()

,Journal_Title,URL,Article_Title,Volume_Issue,Abstract,Keywords,Author_name,Author_Address,Year
0,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Corey Angst,Corey Angst (cangst@nd.edu) is the Jack and Jo...,2024
1,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Alan R. Dennis,Alan R. Dennis (ardennis@iu.edu; corresponding...,2024
2,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Elena Karahanna,Elena Karahanna (ekarah@uga.edu) is Distinguis...,2024
3,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Gondy Leroy,Gondy Leroy (gondyleroy@arizona.edu) is Profes...,2024
4,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Digital Phenotyping-based Depression Detection...,"Volume 41, 2024 - Issue 4",Depression is a growing health and societal pr...,"['Digital phenotyping', 'mobile health analyti...",Fei Peng,Fei Peng is a PhD candidate in the Department ...,2024

In [20]:
df.rename(columns={'Month_Year': 'Volume_Issue'}, inplace=True)

In [24]:
#to drop the unnecessary rows in the data
df_filtered = df[df['Year'] > 2005]

In [23]:
df_filtered.to_excel('JMIS.xlsx',index=False)

In [29]:
#After done the data cleaning using open AI
import pandas as pd
new_data=pd.read_excel('JMIS_Final.xlsx')
new_data.head()

,URL,Article_Title,Journal_Title,Volume_Issue,Year,Abstract,Keywords,Author_name,Author_Address,Author_Email,University,Department,Author_State,Author_Country
0,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Corey Angst,Corey Angst (cangst@nd.edu) is the Jack and Jo...,cangst@nd.edu,University of Notre Dame,Mendoza College of Business,Indiana,United States
1,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Alan R. Dennis,Alan R. Dennis (ardennis@iu.edu; corresponding...,ardennis@iu.edu,Indiana University,Kelley School of Business,Indiana,United States
2,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Elena Karahanna,Elena Karahanna (ekarah@uga.edu) is Distinguis...,ekarah@uga.edu,University of Georgia,Terry College of Business,Georgia,United States
3,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Gondy Leroy,Gondy Leroy (gondyleroy@arizona.edu) is Profes...,gondyleroy@arizona.edu,University of Arizona,Eller College of Management,Arizona,United States
4,https://www.tandfonline.com/doi/full/10.1080/0...,Digital Phenotyping-based Depression Detection...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,Depression is a growing health and societal pr...,"['Digital phenotyping', 'mobile health analyti...",Fei Peng,Fei Peng is a PhD candidate in the Department ...,NaN,Beijing Institute of Technology,Department of Management Engineering,NaN,China

In [30]:
new_data.info() #gives the information about columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2718 entries, 0 to 2717
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   URL             2718 non-null   object
 1   Article_Title   2718 non-null   object
 2   Journal_Title   2718 non-null   object
 3   Volume_Issue    2718 non-null   object
 4   Year            2718 non-null   int64
 5   Abstract        2561 non-null   object
 6   Keywords        2718 non-null   object
 7   Author_name     2718 non-null   object
 8   Author_Address  2717 non-null   object
 9   Author_Email    1125 non-null   object
 10  University      2701 non-null   object
 11  Department      2365 non-null   object
 12  Author_State    2051 non-null   object
 13  Author_Country  2665 non-null   object
dtypes: int64(1), object(13)
memory usage: 297.4+ KB

In [ ]:
new_data.describe() #gives the statisticak values for numerical columns

              Year
count  2718.000000
mean   2014.938558
std       5.674742
min    2005.000000
25%    2010.000000
50%    2015.000000
75%    2020.000000
max    2024.000000

In [13]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')
    
cursor = db.cursor()
# Insert data into MySQL
for index, row in df.iterrows():
    standard_name=row["Standardized_Name"] if row['Standardized_Name'] else None
    # keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    # url=row["URL"] if row['URL'] else None
    # journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    # volume_issue=row["Volume_Issue"] if row['Volume_Issue'] else None
    # month_year=row["Month_Year"] if row['Month_Year'] else None
    # abstract=row["Abstract"] if row['Abstract'] else None
    author_name=row["Author_Name"] if row['Author_Name'] else None
    # author_email=row["Author_Email"] if row['Author_Email'] else None
    # author_address=row["Author_Address"] if row['Author_Address'] else None
    

    try:
        sql = """
        Update Journal_Articles
        set Standardized_Name=%s
        where author_name=%s;
        """
        values = (
            standard_name,author_name
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Vol Issue Year"] if row["Vol Issue Year"] else None

    try:
        sql = """
        INSERT INTO DecisionSupportSystems
        (Title, URL, vol_issue_year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [1]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM Journal_Articles"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("Journal_Articles_new.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_99855/2316557836.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx