In [29]:
import pandas as pd
data=pd.read_csv('JMIS_2025_ArticleData.csv')
data.head()

,Journal_Title,URL,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_Address,Author_email
0,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Hate Speech Detection on Online News Platforms...,Issue 3,"Volume 42, 2025 - Issue 3",Hate speech on online news platforms has emerg...,"['Hate-speech detection', 'design science', 'a...",Seong-Su Kim,Seong-Su Kim (fenzhantw@gmail.com) is data sci...,fenzhantw@gmail.com
1,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Hate Speech Detection on Online News Platforms...,Issue 3,"Volume 42, 2025 - Issue 3",Hate speech on online news platforms has emerg...,"['Hate-speech detection', 'design science', 'a...",Seongbeom Kim,Seongbeom Kim (sb_kim@yonsei.ac.kr)is a PhD ca...,sb_kim@yonsei.ac.kr
2,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Hate Speech Detection on Online News Platforms...,Issue 3,"Volume 42, 2025 - Issue 3",Hate speech on online news platforms has emerg...,"['Hate-speech detection', 'design science', 'a...",Hee-Woong Kim,Hee-Woong Kim (kimhw@yonsei.ac.kr; correspondi...,kimhw@yonsei.ac.kr
3,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Can Correction Messages Reduce the Spread of F...,Issue 3,"Volume 42, 2025 - Issue 3",Although government agencies and fact-checking...,"['Social media', 'fake news', 'news correction...",Kelvin K. King,Kelvin King (kkking@syracuse.edu; correspondin...,kkking@syracuse.edu
4,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Can Correction Messages Reduce the Spread of F...,Issue 3,"Volume 42, 2025 - Issue 3",Although government agencies and fact-checking...,"['Social media', 'fake news', 'news correction...",Diego Escobari,Diego Escobari (diego.escobari@utrgv.edu) is P...,diego.escobari@utrgv.edu

In [30]:
data.drop(columns=['Volume_Issue','Author_email'],inplace=True)

In [31]:
data['Year'] = data['Month_Year'].apply(lambda x: x.split(' ')[2].strip())

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Journal_Title   102 non-null    object
 1   URL             102 non-null    object
 2   Article_Title   102 non-null    object
 3   Month_Year      102 non-null    object
 4   Abstract        102 non-null    object
 5   Keywords        102 non-null    object
 6   Author_name     102 non-null    object
 7   Author_Address  102 non-null    object
 8   Year            102 non-null    object
dtypes: object(9)
memory usage: 7.3+ KB

In [27]:
data.duplicated().sum()

0

In [6]:
data.drop_duplicates(inplace=True)

In [7]:
print(data.info())
print(data.isnull().sum())
print(data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Journal_Title   102 non-null    object
 1   URL             102 non-null    object
 2   Article_Title   102 non-null    object
 3   Volume_Issue    102 non-null    object
 4   Month_Year      102 non-null    object
 5   Abstract        102 non-null    object
 6   Keywords        102 non-null    object
 7   Author_name     102 non-null    object
 8   Author_Address  102 non-null    object
 9   Author_email    101 non-null    object
dtypes: object(10)
memory usage: 8.1+ KB
None
Journal_Title     0
URL               0
Article_Title     0
Volume_Issue      0
Month_Year        0
Abstract          0
Keywords          0
Author_name       0
Author_Address    0
Author_email      1
dtype: int64
                                            Journal_Title  \
count                                                 102
unique                                                  3
top     Journal of Management Information Systems, Vol...
freq                                                   40

                                                      URL  \
count                                                 102
unique                                                 29
top     https://www.tandfonline.com/doi/full/10.1080/0...
freq                                                    6

                                            Article_Title  \
count                                                 102
unique                                                 29
top     Value Drivers for Metaverse Business Models: A...
freq                                                    6

                                             Volume_Issue  \
count                                                 102
unique                                                  3
top     Issue 1: Fostering the Design and Governance o...
freq                                                   40

                                               Month_Year  \
count                                                 102
unique                                                  3
top     Volume 42, 2025 - Issue 1: Fostering the Desig...
freq                                                   40

                                                 Abstract  \
count                                                 102
unique                                                 29
top     The Metaverse has emerged as a prominent topic...
freq                                                    6

                                                 Keywords   Author_name  \
count                                                 102           102
unique                                                 29           102
top     ['Metaverse', 'business models', 'virtual worl...  Seong-Su Kim
freq                                                    6             1

                                           Author_Address         Author_email
count                                                 102                  101
unique                                                102                  101
top     Seong-Su Kim (fenzhantw@gmail.com) is data sci...  fenzhantw@gmail.com
freq                                                    1                    1

In [8]:

df = data.fillna('NULL')

In [17]:
data.head()

,Journal_Title,URL,Article_Title,Month_Year,Abstract,Keywords,Author_name,Author_Address,Year
0,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Hate Speech Detection on Online News Platforms...,"Volume 42, 2025 - Issue 3",Hate speech on online news platforms has emerg...,"['Hate-speech detection', 'design science', 'a...",Seong-Su Kim,Seong-Su Kim (fenzhantw@gmail.com) is data sci...,2025
1,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Hate Speech Detection on Online News Platforms...,"Volume 42, 2025 - Issue 3",Hate speech on online news platforms has emerg...,"['Hate-speech detection', 'design science', 'a...",Seongbeom Kim,Seongbeom Kim (sb_kim@yonsei.ac.kr)is a PhD ca...,2025
2,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Hate Speech Detection on Online News Platforms...,"Volume 42, 2025 - Issue 3",Hate speech on online news platforms has emerg...,"['Hate-speech detection', 'design science', 'a...",Hee-Woong Kim,Hee-Woong Kim (kimhw@yonsei.ac.kr; correspondi...,2025
3,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Can Correction Messages Reduce the Spread of F...,"Volume 42, 2025 - Issue 3",Although government agencies and fact-checking...,"['Social media', 'fake news', 'news correction...",Kelvin K. King,Kelvin King (kkking@syracuse.edu; correspondin...,2025
4,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Can Correction Messages Reduce the Spread of F...,"Volume 42, 2025 - Issue 3",Although government agencies and fact-checking...,"['Social media', 'fake news', 'news correction...",Diego Escobari,Diego Escobari (diego.escobari@utrgv.edu) is P...,2025

In [ ]:
import openai
import pandas as pd
import json
import csv
# openai_api_key = os.getenv("OPENAI_API_KEY")

def extract_author_address(author_address):
    # prompt=f"""
    # Extract the following details from this web journal articles url
    # URL	Author_Name	Standardized_Name	Standardized_University	Author_University	Author_Department	Author_State	Author_Country	Author_Pincode	title
    # # If any detail is missing, return NULL for that field and make sure maintain the same name for field values to search by that. 
    # # ex: in one record US and other record USA and other record contains United States of america display common name for these 3 record values. Same for university, department, state names also if Wichita State University in one record and WSU in other record display common name to use in search operation in my website. 
    # # If it is common name I can search easily.
    
    # # URL: {address}
    
    # # Return the data in JSON format.
    # """

   prompt = f"""
        Extract, standardize, and enrich the following author and university information. 
        Your task is to ensure consistent, deduplicated, and accurate naming across all data.

        IMPORTANT REQUIREMENTS:
        1. **Author Names**
        - Convert all names to English alphabet (transliterate non-English characters).
        - Apply title case (First Last).
        - Standardize across variations:
            - "P Prakash" → "Ponduri Prakash"
            - "Dr. John Smith" → "John Smith"
            - "Smith, John" → "John Smith"
            - "J. Smith" and "John Smith" → "John Smith"
        - Ensure one unique standardized name appears everywhere for the same person.

        2. **University Names**
        - Standardize and unify variations to the official English name.
            - Example: "WSU", "Wichita Statte University", "Wichita State University USA" 
            → "Wichita State University"
        - Translate foreign-language university names to their official English equivalent.
        - Always return the same name for the same university across records.

        3. **Location Data (State & Country)**
        - Standardize country names to official English (e.g., US/USA → "United States").
        - Standardize state/province names (e.g., CA → "California").
        - If missing, determine the correct **state and country** for the given university 
            using external knowledge (Google, world university data).
        - Ensure consistency: the same university must always map to the same state and country.

       
        CRITICAL:
        - Return only a single JSON object (not an array).
        - Use English-only text in final output.
        - Make sure author, university, state, and country are 100% consistent across all rows.

        Text to process: {author_address}

        Output format:
        {{
            "Author": "Ponduri Prakash",
            "Standardized_Author": "Ponduri Prakash", 
            "University": "Wichita State University",
            "Department": "Computer Science",
            "State": "Kansas",
            "Country": "United States",
            "Pincode": "67260"
        }}"""
   response=openai.chat.completions.create(
        model='gpt-3.5-turbo',
        messages=[
            {"role":"system","content":"You are an expert in structured data extraction."},
            {"role":"user","content":prompt}
        ],
        temperature=0
    )
   try:
        extracted_data=response.choices[0].message.content.strip().strip('```json').strip('```')
        structured_data=json.loads(extracted_data)
        author_data={
        'Standardized_Author': structured_data.get('Standardized_Author', None),
        'University': structured_data.get('University', None),
        # 'Department': structured_data.get('Department', None),
        'State': structured_data.get('State', None),
        'Country': structured_data.get('Country', None),
        # 'Pincode': structured_data.get('Pincode', None) # assuming pincode is always present in the structured data. If not, return None.
        }
        return author_data 
   except Exception as e:
        print(e)
   return None


with open('extract_2025.csv', mode='a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['URL','Journal_Title','Month_Year','Abstract','Keywords','Author_name','Standardized_Author','Author_Address','Author_University','Author_State','Author_Country'])
for index,row in data.iterrows():
    address=row['Author_Address']
    Author_name=row['Author_name']

    result = extract_author_address(Author_name+address)
    with open('extract_2025.csv', mode='a', newline='',encoding='utf-8') as file:
        writer=csv.writer(file)
        writer.writerow([row['URL'],row['Journal_Title'],row['Year'],row['Abstract'],row['Keywords'],row['Author_name'],result['Standardized_Author'],row['Author_Address'],result['University'],result['State'],result['Country']])

In [ ]:
data.duplicated(subset=['URL','Author_name']).sum()
data.drop_duplicates(subset=['URL','Author_name'],inplace=True)

In [ ]:
data.duplicated(subset=['URL','Author_name']).sum()

0

In [ ]:
data.to_excel('JMIS_Final.xlsx')

In [ ]:
df = data.where(pd.notna(data), None)

In [ ]:
df = data.replace("", None)  # Replaces empty spaces with None

In [ ]:
df['Year'] = df['Month_Year'].apply(lambda x: x.split(',')[1].strip().split()[0])
df['Year'] = df['Year'].astype(int)

In [ ]:
df.head()

,Journal_Title,URL,Article_Title,Volume_Issue,Abstract,Keywords,Author_name,Author_Address,Year
0,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Corey Angst,Corey Angst (cangst@nd.edu) is the Jack and Jo...,2024
1,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Alan R. Dennis,Alan R. Dennis (ardennis@iu.edu; corresponding...,2024
2,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Elena Karahanna,Elena Karahanna (ekarah@uga.edu) is Distinguis...,2024
3,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Volume 41, 2024 - Issue 4",NaN,[],Gondy Leroy,Gondy Leroy (gondyleroy@arizona.edu) is Profes...,2024
4,"Journal of Management Information Systems, Vol...",https://www.tandfonline.com/doi/full/10.1080/0...,Digital Phenotyping-based Depression Detection...,"Volume 41, 2024 - Issue 4",Depression is a growing health and societal pr...,"['Digital phenotyping', 'mobile health analyti...",Fei Peng,Fei Peng is a PhD candidate in the Department ...,2024

In [ ]:
df.rename(columns={'Month_Year': 'Volume_Issue'}, inplace=True)

In [ ]:
#to drop the unnecessary rows in the data
df_filtered = df[df['Year'] > 2005]

In [ ]:
df_filtered.to_excel('JMIS.xlsx',index=False)

In [ ]:
#After done the data cleaning using open AI
import pandas as pd
new_data=pd.read_excel('JMIS_Final.xlsx')
new_data.head()

,URL,Article_Title,Journal_Title,Volume_Issue,Year,Abstract,Keywords,Author_name,Author_Address,Author_Email,University,Department,Author_State,Author_Country
0,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Corey Angst,Corey Angst (cangst@nd.edu) is the Jack and Jo...,cangst@nd.edu,University of Notre Dame,Mendoza College of Business,Indiana,United States
1,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Alan R. Dennis,Alan R. Dennis (ardennis@iu.edu; corresponding...,ardennis@iu.edu,Indiana University,Kelley School of Business,Indiana,United States
2,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Elena Karahanna,Elena Karahanna (ekarah@uga.edu) is Distinguis...,ekarah@uga.edu,University of Georgia,Terry College of Business,Georgia,United States
3,https://www.tandfonline.com/doi/full/10.1080/0...,Special Section: Information Technology to Imp...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,NaN,[],Gondy Leroy,Gondy Leroy (gondyleroy@arizona.edu) is Profes...,gondyleroy@arizona.edu,University of Arizona,Eller College of Management,Arizona,United States
4,https://www.tandfonline.com/doi/full/10.1080/0...,Digital Phenotyping-based Depression Detection...,"Journal of Management Information Systems, Vol...","Volume 41, 2024 - Issue 4",2024,Depression is a growing health and societal pr...,"['Digital phenotyping', 'mobile health analyti...",Fei Peng,Fei Peng is a PhD candidate in the Department ...,NaN,Beijing Institute of Technology,Department of Management Engineering,NaN,China

In [ ]:
new_data.info() #gives the information about columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2718 entries, 0 to 2717
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   URL             2718 non-null   object
 1   Article_Title   2718 non-null   object
 2   Journal_Title   2718 non-null   object
 3   Volume_Issue    2718 non-null   object
 4   Year            2718 non-null   int64
 5   Abstract        2561 non-null   object
 6   Keywords        2718 non-null   object
 7   Author_name     2718 non-null   object
 8   Author_Address  2717 non-null   object
 9   Author_Email    1125 non-null   object
 10  University      2701 non-null   object
 11  Department      2365 non-null   object
 12  Author_State    2051 non-null   object
 13  Author_Country  2665 non-null   object
dtypes: int64(1), object(13)
memory usage: 297.4+ KB

In [ ]:
new_data.describe() #gives the statisticak values for numerical columns

              Year
count  2718.000000
mean   2014.938558
std       5.674742
min    2005.000000
25%    2010.000000
50%    2015.000000
75%    2020.000000
max    2024.000000

In [ ]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')
    
cursor = db.cursor()
# Insert data into MySQL
for index, row in df.iterrows():
    standard_name=row["Standardized_Name"] if row['Standardized_Name'] else None
    # keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    # url=row["URL"] if row['URL'] else None
    # journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    # volume_issue=row["Volume_Issue"] if row['Volume_Issue'] else None
    # month_year=row["Month_Year"] if row['Month_Year'] else None
    # abstract=row["Abstract"] if row['Abstract'] else None
    author_name=row["Author_Name"] if row['Author_Name'] else None
    # author_email=row["Author_Email"] if row['Author_Email'] else None
    # author_address=row["Author_Address"] if row['Author_Address'] else None
    

    try:
        sql = """
        Update Journal_Articles
        set Standardized_Name=%s
        where author_name=%s;
        """
        values = (
            standard_name,author_name
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [ ]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Vol Issue Year"] if row["Vol Issue Year"] else None

    try:
        sql = """
        INSERT INTO DecisionSupportSystems
        (Title, URL, vol_issue_year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [ ]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM Journal_Articles"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("Journal_Articles_new.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_99855/2316557836.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx