In [19]:
import pandas as pd
data=pd.read_csv('extract.csv')
data.head()

,URL,Journal_Title,Article_Title,Volume_Issue,Abstract,Keywords,Author_name,Standardized_Author,Author_email,Author_Address,Author_University,Author_department,Author_State,Author_Country,Author_pincode
0,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Responsible artificial intelligence governance...,"Volume 34, Issue 2",•\nSynthesizes empirical studies on responsibl...,"['Artificial intelligence', 'Responsible AI go...",Emmanouil Papagiannidis,Emmanouil Papagiannidis,emmanouil.papagiannidis@ntnu.no,"Department of Computer Science, Norwegian Univ...",Norwegian University of Science and Technology,Computer Science,Sor-Trondelag,Norway,NaN
1,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Responsible artificial intelligence governance...,"Volume 34, Issue 2",•\nSynthesizes empirical studies on responsibl...,"['Artificial intelligence', 'Responsible AI go...",Patrick Mikalef,Patrick Mikalef,patrick.mikalef@ntnu.no,"Department of Computer Science, Norwegian Univ...",Norwegian University of Science and Technology,Computer Science,Sor-Trondelag,Norway,NaN
2,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Responsible artificial intelligence governance...,"Volume 34, Issue 2",•\nSynthesizes empirical studies on responsibl...,"['Artificial intelligence', 'Responsible AI go...",Kieran Conboy,Kieran Conboy,kieran.conboy@nuigalway.ie,"School of Business & Economics, National Unive...","National University of Ireland, Galway",School of Business & Economics,Galway,Ireland,NaN
3,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,The complementary and substitutional effects o...,"Volume 34, Issue 1",•\nInformation systems multisourcing requires ...,"['Multisourcing', 'Competition', 'Cooperation'...",Eleni Lioliou,Eleni Lioliou,e.lioliou@qmul.ac.uk,"Queen Mary University of London, Mile End Road...",Queen Mary University of London,NaN,London,United Kingdom,E1 4NS
4,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,The complementary and substitutional effects o...,"Volume 34, Issue 1",•\nInformation systems multisourcing requires ...,"['Multisourcing', 'Competition', 'Cooperation'...",Oliver Krancher,Oliver Krancher,olik@itu.dk,"IT University of Copenhagen, Rued Langgaards V...",IT University of Copenhagen,NaN,Capital Region,Denmark,2300

In [20]:
data = data.where(pd.notna(data), None)

In [21]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1791 entries, 0 to 1790
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   URL                  1791 non-null   object
 1   Journal_Title        1791 non-null   object
 2   Article_Title        1791 non-null   object
 3   Volume_Issue         1791 non-null   object
 4   Abstract             1738 non-null   object
 5   Keywords             1791 non-null   object
 6   Author_name          1791 non-null   object
 7   Standardized_Author  1791 non-null   object
 8   Author_email         1099 non-null   object
 9   Author_Address       1791 non-null   object
 10  Author_University    1784 non-null   object
 11  Author_department    1183 non-null   object
 12  Author_State         1743 non-null   object
 13  Author_Country       1791 non-null   object
 14  Author_pincode       1136 non-null   object
dtypes: object(15)
memory usage: 210.0+ KB
None

In [22]:
print(data.isnull().sum())
print(data.describe())
data=data.fillna('Null')

URL                      0
Journal_Title            0
Article_Title            0
Volume_Issue             0
Abstract                53
Keywords                 0
Author_name              0
Standardized_Author      0
Author_email           692
Author_Address           0
Author_University        7
Author_department      608
Author_State            48
Author_Country           0
Author_pincode         655
dtype: int64
                                                      URL  \
count                                                1791
unique                                                796
top     https://www.sciencedirect.com/science/article/...
freq                                                    6

                                       Journal_Title Article_Title  \
count                                           1791          1791
unique                                             1           707
top     The Journal of Strategic Information Systems     Editorial
freq                                            1791            97

              Volume_Issue            Abstract Keywords   Author_name  \
count                 1791                1738     1791          1791
unique                 133                 617       47          1306
top     Volume 20, Issue 4  No articles found.       []  Bob Galliers
freq                    27                  91     1642            44

       Standardized_Author           Author_email           Author_Address  \
count                 1791                   1099                     1791
unique                1246                    922                     1232
top           Bob Galliers  rgalliers@bentley.edu  Bentley University, USA
freq                    45                     11                       26

         Author_University Author_department Author_State Author_Country  \
count                 1784              1183         1743           1791
unique                 576               418          227             47
top     Bentley University   Business School        Texas  United States
freq                    55               102          100            523

       Author_pincode
count            1136
unique            490
top           CV4 7AL
freq               35

In [2]:
#The first version to get the years of articles
import pandas as pd
df=pd.read_csv('Journal_of_SIS.csv')
df['Year'] = df['Month_Year'].apply(lambda x: x.split(" ")[-1])
df.head()
# Convert manually after reading

,Title,URL,Volume Issue,Month_Year,Year
0,Responsible artificial intelligence governance...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 2",01 June 2025,2025
1,The complementary and substitutional effects o...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
2,A socio-cognitive perspective of knowledge int...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
3,A process model for design-oriented machine le...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
4,A knowledge-centric model for government-orche...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1048 non-null   object
 1   URL           1048 non-null   object
 2   Volume Issue  1048 non-null   object
 3   Month_Year    1048 non-null   object
 4   Year          1048 non-null   object
dtypes: object(5)
memory usage: 41.1+ KB

In [4]:

df = df.fillna('NULL')

In [8]:
# print(data['Author_Country'].value_counts())

In [5]:
df.duplicated().sum()

0

In [6]:
df.head()

,Title,URL,Volume Issue,Month_Year,Year
0,Responsible artificial intelligence governance...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 2",01 June 2025,2025
1,The complementary and substitutional effects o...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
2,A socio-cognitive perspective of knowledge int...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
3,A process model for design-oriented machine le...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
4,A knowledge-centric model for government-orche...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025

In [24]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

cursor = db.cursor()
# Insert data into MySQL
for index, row in data.iterrows():
    url=row["URL"] if row['URL'] else None
    article_title=row["Article_Title"] if row['Article_Title'] else None
    journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    abstract=row["Abstract"] if row['Abstract'] else None
    keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    # month_year=row["Month_Year"] if row['Month_Year'] else None
    author_name=row["Author_name"] if row['Author_name'] else None
    standard_name=row["Standardized_Author"] if row['Standardized_Author'] else None
    author_email=row["Author_email"] if row['Author_email'] else None
    author_address=row["Author_Address"] if row['Author_Address'] else None
    author_university=row["Author_University"] if row['Author_University'] else None
    author_department=row["Author_department"] if row['Author_department'] else None
    author_state=row["Author_State"] if row['Author_State'] else None  #   
    author_country=row["Author_Country"] if row['Author_Country'] else None
        
    try:
        sql = """
        INSERT INTO JSIS(URL,Journal_Title,Article_Title,Abstract,Keywords,Author_Name,Standardized_Author,Author_Email,Author_Address,Author_University,Author_Department,Author_State,Author_Country) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """
        values = (
            url,journal_title,article_title,abstract,keywords,author_name,standard_name,author_email,author_address,author_university,author_department,author_state,author_country
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Year"] if row["Year"] else None

    try:
        sql = """
        INSERT INTO JSIS_Articles
        (Article_Title, URL, Month_Year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [25]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM JSIS"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("JSIS_final.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_31214/922654084.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx