In [1]:
import pandas as pd
data=pd.read_csv('JSIS_2025_ArticleData.csv')
data.head()

,URL,Journal_Title,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_email,Author_Address
0,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Digital transformation by outflanking: How per...,"Volume 35, Issue 1",2026,NaN,"['Digital transformation', 'Organizational tra...",Viktor Arvidsson,viktor.arvidsson@liu.se,"Department of Management and Engineering, Info..."
1,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Digital transformation by outflanking: How per...,"Volume 35, Issue 1",2026,NaN,"['Digital transformation', 'Organizational tra...",Jonny Holmström,jonny.holmstrom@umu.se,"Swedish Center for Digital Innovation, Departm..."
2,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Digital transformation by outflanking: How per...,"Volume 35, Issue 1",2026,NaN,"['Digital transformation', 'Organizational tra...",Kalle Lyytinen,kjl13@case.edu,"Case Western Reserve University, Weatherhead S..."
3,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...","Volume 35, Issue 1",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Inmyung Choi,inmyung.choi@ttu.edu,Information Systems and Quantitative Sciences ...
4,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...","Volume 35, Issue 1",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Alain Pinsonneault,alain.pinsonneault@mcgill.ca,"Desautels Faculty of Management, McGill Univer..."

In [2]:
data=data.iloc[1:]

In [3]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 1 to 96
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   URL             96 non-null     object
 1   Journal_Title   96 non-null     object
 2   Article_Title   96 non-null     object
 3   Volume_Issue    96 non-null     object
 4   Month_Year      96 non-null     int64
 5   Abstract        0 non-null      float64
 6   Keywords        96 non-null     object
 7   Author_name     93 non-null     object
 8   Author_email    72 non-null     object
 9   Author_Address  93 non-null     object
dtypes: float64(1), int64(1), object(8)
memory usage: 7.6+ KB
None

In [4]:
data.head()

,URL,Journal_Title,Article_Title,Volume_Issue,Month_Year,Abstract,Keywords,Author_name,Author_email,Author_Address
1,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Digital transformation by outflanking: How per...,"Volume 35, Issue 1",2026,NaN,"['Digital transformation', 'Organizational tra...",Jonny Holmström,jonny.holmstrom@umu.se,"Swedish Center for Digital Innovation, Departm..."
2,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Digital transformation by outflanking: How per...,"Volume 35, Issue 1",2026,NaN,"['Digital transformation', 'Organizational tra...",Kalle Lyytinen,kjl13@case.edu,"Case Western Reserve University, Weatherhead S..."
3,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...","Volume 35, Issue 1",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Inmyung Choi,inmyung.choi@ttu.edu,Information Systems and Quantitative Sciences ...
4,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...","Volume 35, Issue 1",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Alain Pinsonneault,alain.pinsonneault@mcgill.ca,"Desautels Faculty of Management, McGill Univer..."
5,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...","Volume 35, Issue 1",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Kunsoo Han,kunsoo.han@mcgill.ca,"Desautels Faculty of Management, McGill Univer..."

In [5]:
data.drop(columns=['Volume_Issue'])

,URL,Journal_Title,Article_Title,Month_Year,Abstract,Keywords,Author_name,Author_email,Author_Address
1,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Digital transformation by outflanking: How per...,2026,NaN,"['Digital transformation', 'Organizational tra...",Jonny Holmström,jonny.holmstrom@umu.se,"Swedish Center for Digital Innovation, Departm..."
2,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Digital transformation by outflanking: How per...,2026,NaN,"['Digital transformation', 'Organizational tra...",Kalle Lyytinen,kjl13@case.edu,"Case Western Reserve University, Weatherhead S..."
3,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Inmyung Choi,inmyung.choi@ttu.edu,Information Systems and Quantitative Sciences ...
4,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Alain Pinsonneault,alain.pinsonneault@mcgill.ca,"Desautels Faculty of Management, McGill Univer..."
5,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,"IT investment differentiation, strategic disti...",2026,NaN,"['IT investment differentiation', 'Excess IT i...",Kunsoo Han,kunsoo.han@mcgill.ca,"Desautels Faculty of Management, McGill Univer..."
...,...,...,...,...,...,...,...,...,...
92,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,A knowledge-centric model for government-orche...,2025,NaN,"['Digital transformation', 'Government', 'Publ...",John O’Shanahan,oshanahan.john@ul.ie,"University of Limerick, Castletroy, Co. Limeri..."
93,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Unboxing maturity models: A set-theoretic pers...,2025,NaN,[],F. Iannacci,F.Iannacci@sussex.ac.uk,"Department of Management, Business School, Uni..."
94,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Unboxing maturity models: A set-theoretic pers...,2025,NaN,[],S. Karanasios,NaN,"University of Queensland Business School, Univ..."
95,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Unboxing maturity models: A set-theoretic pers...,2025,NaN,[],R. McManus,NaN,"Christ Church Business School, Canterbury Chri..."
96,https://www.sciencedirect.com/science/article/...,The Journal of Strategic Information Systems,Unboxing maturity models: A set-theoretic pers...,2025,NaN,[],C. Rupietta,NaN,"Queen's Business School, Queen's University Be..."

In [6]:
print(data.isnull().sum())
print(data.describe())
data=data.fillna('Null')

URL                0
Journal_Title      0
Article_Title      0
Volume_Issue       0
Month_Year         0
Abstract          96
Keywords           0
Author_name        3
Author_email      24
Author_Address     3
dtype: int64
        Month_Year  Abstract
count    96.000000       0.0
mean   2025.052083       NaN
std       0.223361       NaN
min    2025.000000       NaN
25%    2025.000000       NaN
50%    2025.000000       NaN
75%    2025.000000       NaN
max    2026.000000       NaN

In [7]:
#delete the rows whwere author_name is null
data=data[data['Author_name']!='Null']

In [8]:
data.isnull().sum()
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 96
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   URL             93 non-null     object
 1   Journal_Title   93 non-null     object
 2   Article_Title   93 non-null     object
 3   Volume_Issue    93 non-null     object
 4   Month_Year      93 non-null     int64
 5   Abstract        93 non-null     object
 6   Keywords        93 non-null     object
 7   Author_name     93 non-null     object
 8   Author_email    93 non-null     object
 9   Author_Address  93 non-null     object
dtypes: int64(1), object(9)
memory usage: 8.0+ KB

In [ ]:
import openai
import pandas as pd
import json
import csv
import os
openai_api_key = os.getenv("OPENAI_API_KEY")
# print(openai_api_key)

def extract_author_address(author_address):
    # prompt=f"""
    # Extract the following details from this web journal articles url
    # URL	Author_Name	Standardized_Name	Standardized_University	Author_University	Author_Department	Author_State	Author_Country	Author_Pincode	title
    # # If any detail is missing, return NULL for that field and make sure maintain the same name for field values to search by that. 
    # # ex: in one record US and other record USA and other record contains United States of america display common name for these 3 record values. Same for university, department, state names also if Wichita State University in one record and WSU in other record display common name to use in search operation in my website. 
    # # If it is common name I can search easily.
    
    # # URL: {address}
    
    # # Return the data in JSON format.
    # """

    prompt = f"""
    Extract and standardize the following details from the given text containing author information:
    
    
        IMPORTANT LANGUAGE REQUIREMENTS:
        - Convert ALL text to English equivalents
        - Transliterate non-English characters to English alphabet (e.g., ñ→n, ü→u, é→e, ç→c)
        - Translate foreign language university names to their official English names
        - If university has both local and English names, use the English version
        - For author names with non-English characters, provide romanized/English alphabet version
        
        Fields to extract:
        - Author: Full name as mentioned in the text (converted to English alphabet)
        - Standardized_Author: Normalized English version for deduplication (follow rules below)
        - University: Full university name in English (standardize abbreviations and translate foreign names)
        - Department: Academic department in English (if mentioned, otherwise null)
        - State: State/province in English where the university is located
        - Country: Country name in standard English
        - Pincode: Postal/ZIP code (if mentioned, otherwise null)

        Author Name Standardization Rules:
        1. Convert to English alphabet (transliterate non-English characters)
        2. Use title case (First Letter Capitalized For Each Word)
        3. For names like "Rajesh R" and "Rajesh Raj" - if first name + first letter of last name matches, use the longer version
        4. Remove middle initials if a full middle name exists elsewhere for same person
        5. Handle common variations:
        - "Dr. John Smith" → "John Smith"
        - "Prof. Jane Doe" → "Jane Doe" 
        - "Smith, John" → "John Smith"
        - "J. Smith" vs "John Smith" → use "John Smith" if both refer to same person
        6. Remove extra spaces and special characters
        7. Convert accented characters: José → Jose, François → Francois, etc.

        University/Location Standardization Examples:
        - Universidad Politécnica de Madrid → "Technical University of Madrid"
        - WSU → "Wichita State University"
        - MIT → "Massachusetts Institute of Technology"
        - École Polytechnique → "Polytechnic School"
        - Université de Paris → "University of Paris"
        - Tsinghua Daxue → "Tsinghua University"
        - Universidad Nacional de Colombia → "National University of Colombia"
        - Technische Universität München → "Technical University of Munich"
        
        Country Standardization:
        - US/USA/United States/Estados Unidos → "United States"
        - UK/United Kingdom/Inglaterra → "United Kingdom"  
        - Deutschland/Alemania → "Germany"
        - España → "Spain"
        - França/France → "France"
        - Use full English country names

        State Standardization:
        - Use full English state/province names
        - CA → "California", NY → "New York", etc.
        - Convert regional names to English equivalents

        Text to process: {author_address}

        CRITICAL: Return ONLY as a single JSON object (not array) with English text only. Example format:
        {{
            "Author": "Jose Martinez",
            "Standardized_Author": "Jose Martinez", 
            "University": "Technical University of Madrid",
            "Department": "Computer Science",
            "State": "Madrid",
            "Country": "Spain",
            "Pincode": "28040"
        }}"""
    response=openai.chat.completions.create(
        model='gpt-3.5-turbo',
        messages=[
            {"role":"system","content":"You are an expert in structured data extraction."},
            {"role":"user","content":prompt}
        ],
        temperature=0
    )
    extracted_data=response.choices[0].message.content.strip().strip('```json').strip('```')
    try:
        structured_data=json.loads(extracted_data)
    except Exception as e:
        print(e)
    author_data={
        'Standardized_Author': structured_data.get('Standardized_Author', None),
        'University': structured_data.get('University', None),
        'Department': structured_data.get('Department', None),
        'State': structured_data.get('State', None),
        'Country': structured_data.get('Country', None),
        'Pincode': structured_data.get('Pincode', None) # assuming pincode is always present in the structured data. If not, return None.
    }  
    return author_data


with open('extract_2025.csv', mode='a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['URL','Journal_Title','Article_Title','Abstract','Keywords','Author_name','Standardized_Author','Author_email','Author_Address','Author_University','Author_department','Author_State','Author_Country','Author_pincode'])
for index,row in data.iterrows():
    address=row['Author_name']+row['Author_Address']
    result = extract_author_address(address)
    with open('extract_2025.csv', mode='a', newline='',encoding='utf-8') as file:
        writer=csv.writer(file)
        writer.writerow([row['URL'],row['Journal_Title'],row['Article_Title'],row['Abstract'],row['Keywords'],row['Author_name'],result['Standardized_Author'],row['Author_email'],row['Author_Address'],result['University'],result['Department'],result['State'],result['Country'],result['Pincode']])

In [2]:
#The first version to get the years of articles
import pandas as pd
df=pd.read_csv('Journal_of_SIS.csv')
df['Year'] = df['Month_Year'].apply(lambda x: x.split(" ")[-1])
df.head()
# Convert manually after reading

,Title,URL,Volume Issue,Month_Year,Year
0,Responsible artificial intelligence governance...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 2",01 June 2025,2025
1,The complementary and substitutional effects o...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
2,A socio-cognitive perspective of knowledge int...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
3,A process model for design-oriented machine le...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
4,A knowledge-centric model for government-orche...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1048 non-null   object
 1   URL           1048 non-null   object
 2   Volume Issue  1048 non-null   object
 3   Month_Year    1048 non-null   object
 4   Year          1048 non-null   object
dtypes: object(5)
memory usage: 41.1+ KB

In [4]:

df = df.fillna('NULL')

In [8]:
# print(data['Author_Country'].value_counts())

In [29]:
data.duplicated().sum()

0

In [6]:
df.head()

,Title,URL,Volume Issue,Month_Year,Year
0,Responsible artificial intelligence governance...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 2",01 June 2025,2025
1,The complementary and substitutional effects o...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
2,A socio-cognitive perspective of knowledge int...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
3,A process model for design-oriented machine le...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
4,A knowledge-centric model for government-orche...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025

In [24]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

cursor = db.cursor()
# Insert data into MySQL
for index, row in data.iterrows():
    url=row["URL"] if row['URL'] else None
    article_title=row["Article_Title"] if row['Article_Title'] else None
    journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    abstract=row["Abstract"] if row['Abstract'] else None
    keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    # month_year=row["Month_Year"] if row['Month_Year'] else None
    author_name=row["Author_name"] if row['Author_name'] else None
    standard_name=row["Standardized_Author"] if row['Standardized_Author'] else None
    author_email=row["Author_email"] if row['Author_email'] else None
    author_address=row["Author_Address"] if row['Author_Address'] else None
    author_university=row["Author_University"] if row['Author_University'] else None
    author_department=row["Author_department"] if row['Author_department'] else None
    author_state=row["Author_State"] if row['Author_State'] else None  #   
    author_country=row["Author_Country"] if row['Author_Country'] else None
        
    try:
        sql = """
        INSERT INTO JSIS(URL,Journal_Title,Article_Title,Abstract,Keywords,Author_Name,Standardized_Author,Author_Email,Author_Address,Author_University,Author_Department,Author_State,Author_Country) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """
        values = (
            url,journal_title,article_title,abstract,keywords,author_name,standard_name,author_email,author_address,author_university,author_department,author_state,author_country
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Year"] if row["Year"] else None

    try:
        sql = """
        INSERT INTO JSIS_Articles
        (Article_Title, URL, Month_Year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [25]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM JSIS"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("JSIS_final.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_31214/922654084.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx

In [2]:
import pandas as pd
jsis_2025_data=pd.read_csv('extract_2025.csv')
jsis_2025_article_data=pd.read_csv('JSIS_2025_ArticleData.csv')

In [9]:
jsis_2025_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   URL                  93 non-null     object
 1   Journal_Title        93 non-null     object
 2   Article_Title        93 non-null     object
 3   Abstract             93 non-null     object
 4   Keywords             93 non-null     object
 5   Author_name          93 non-null     object
 6   Standardized_Author  93 non-null     object
 7   Author_email         93 non-null     object
 8   Author_Address       93 non-null     object
 9   Author_University    93 non-null     object
 10  Author_department    65 non-null     object
 11  Author_State         93 non-null     object
 12  Author_Country       93 non-null     object
 13  Author_pincode       38 non-null     object
dtypes: object(14)
memory usage: 10.3+ KB

In [10]:
jsis_2025_article_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95 entries, 0 to 96
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   URL             95 non-null     object
 1   Journal_Title   95 non-null     object
 2   Article_Title   95 non-null     object
 3   Volume_Issue    95 non-null     object
 4   Month_Year      95 non-null     int64
 5   Abstract        0 non-null      float64
 6   Keywords        95 non-null     object
 7   Author_name     94 non-null     object
 8   Author_email    73 non-null     object
 9   Author_Address  94 non-null     object
dtypes: float64(1), int64(1), object(8)
memory usage: 8.2+ KB

In [11]:
jsis_2025_data.groupby(['Author_Country'])['URL'].count()

Author_Country
Australia            15
Canada               10
China                 4
Denmark               1
Finland               1
France                2
Germany              17
Hong Kong             1
Ireland               7
Italy                 1
New Zealand           4
Norway                2
Republic of Korea     4
South Korea           1
Sweden                1
United Kingdom        9
United States        13
Name: URL, dtype: int64

In [14]:
# Merge df1 with df2 on the common column 'URL'
merged_2025 = jsis_2025_data.merge(jsis_2025_article_data[['URL', 'Month_Year']], on='URL', how='left')

In [15]:
merged_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355 entries, 0 to 354
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   URL                  355 non-null    object
 1   Journal_Title        355 non-null    object
 2   Article_Title        355 non-null    object
 3   Abstract             355 non-null    object
 4   Keywords             355 non-null    object
 5   Author_name          355 non-null    object
 6   Standardized_Author  355 non-null    object
 7   Author_email         355 non-null    object
 8   Author_Address       355 non-null    object
 9   Author_University    355 non-null    object
 10  Author_department    215 non-null    object
 11  Author_State         355 non-null    object
 12  Author_Country       355 non-null    object
 13  Author_pincode       163 non-null    object
 14  Month_Year           355 non-null    int64
dtypes: int64(1), object(14)
memory usage: 41.7+ KB